### ISSUE TITLE
SERIAL_TX_ONLY in HardwareSerial.begin()

### ISSUE THREAD

**Issue by RayPS** [1452206376/CH9328-Keyboard#3]
作者你好，祝你春节愉快。
感谢你制作的 CH9328 库，我已经在多个项目中使用并享受此库。

我遇到一个问题，当 `Keyboard.begin` 初始化之后，ESP8266 的 RX 将无法被上拉。
由于 CH9328 只需要用到 TX，所以 `begin` 这里的 `SerialMode` 是否可以启用 `SERIAL_TX_ONLY` 呢？
因为默认是 `SERIAL_FULL` 将会同时使用 RX 和 TX。

https://github.com/lxydiy/CH9328-Keyboard/blob/fddd452c686e95faea44781d62e0992be411889c/src/CH9328Keyboard.cpp#L39

另外，README 中提到的 IO9 的 BUG 我也遇到了，在 `loop()` 中加入 `ESP.wdtDisable();` 可以使 IO9 用作输入。

**Comment by ghost** [comment]
Hi,
Thank you very much for telling me this issue.

It may works. But I can't test it now. Because I don't have any CH9328 chip available. It is Chinese New Year now, so my online order can't be delievered to my home these day. I wish you can help me testing. If it works, please make a Pull Request, so that I can make a newer version of it.

Happy Chinese New Year to you! Wish you have a healthy body.
And thank you for your contribution to Open Source Community!
----
The following is the raw version in Chinese. I think my English skill is OK, and I think your mother language isn't Chinese. So I translated it for you :P
(But I didn't translate it directly. [doge])
----
谢谢您提出这个问题。
应该可以，但是这会儿过年不发货，没法测试。之前DIY的在学校一体机上，寒假拿不回来。您那里如果有可以测试一下，没问题的话希望您能提交PR，我好更新版本。

**Comment by RayPS** [comment]
你好，感谢你的贡献。我已经修改了上述提出的变更并提交了 PR，经过测试确认修复此问题，另外把版本号提升为 `1.0.2`。
合并之后可以关闭此 Issue。

**Comment by zfzwy** [comment]
新年快乐，我想问一下，这个库只能模拟键盘吗？不能鼠标键盘都模拟出来吗？

**Comment by ghost** [comment]
> 新年快乐，我想问一下，这个库只能模拟键盘吗？不能鼠标键盘都模拟出来吗？

CH9328只支持键盘，CH9329支持键盘鼠标
